# Generated by Django 4.2 on 2023-04-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0005_country_alter_address_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='published_country',
        ),
        migrations.AddField(
            model_name='book',
            name='published_country',
            field=models.ManyToManyField(to='book_outlet.country'),
        ),
    ]
